export const LESSONS = [
  {
    id: "anime-intro",
    title: "Anime Dialogue: First Encounter",
    theme: "anime dialogue",
    difficulty: "N5",
    japanese: "はじめまして。今日はよろしくお願いします。こちらこそ、お願いします。",
    romaji: "Hajimemashite. Kyou wa yoroshiku onegaishimasu. Kochirakoso, onegaishimasu.",
    translation: "Nice to meet you. Please treat me kindly today. Likewise, thank you.",
    grammar: "Polite introductions, reciprocal politeness with こちらこそ, and 〜お願いします for gentle requests.",
    vocab: [
      { word: "はじめまして", kana: "はじめまして", meaning: "nice to meet you" },
      { word: "今日", kana: "きょう", meaning: "today" },
      { word: "よろしく", kana: "よろしく", meaning: "please treat me well / kindly" },
      { word: "こちらこそ", kana: "こちらこそ", meaning: "likewise / same to you" },
      { word: "お願いします", kana: "おねがいします", meaning: "please / I request" },
    ],
    kanji: ["今", "名", "願"],
    dialogueLines: [
      { speaker: "Narration", text: "A first meeting at a school club." },
      { speaker: "A", text: "はじめまして。今日はよろしくお願いします。" },
      { speaker: "B", text: "こちらこそ、よろしくお願いします。" },
      { speaker: "A", text: "名前を教えてください。" },
      { speaker: "B", text: "たなかです。どうぞよろしく。" },
    ],
    grammarPoints: [
      {
        title: "はじめまして",
        explanation: "Use this when meeting someone for the first time.",
        example: "はじめまして。今日はよろしくお願いします。",
      },
      {
        title: "こちらこそ",
        explanation: "Use this to say 'likewise' or 'same to you.'",
        example: "こちらこそ、よろしくお願いします。",
      },
      {
        title: "〜お願いします",
        explanation: "A polite way to ask for cooperation or a request.",
        example: "今日はよろしくお願いします。",
      },
    ],
    exercises: [
      {
        id: "anime-intro-exercise-1",
        type: "multiple-choice",
        prompt: "Which phrase fits a first-time introduction?",
        choices: ["はじめまして", "おはようございます", "ただいま", "おつかれさまです"],
        answer: "はじめまして",
        explanation: "はじめまして is used when meeting someone for the first time.",
      },
      {
        id: "anime-intro-exercise-2",
        type: "translation",
        prompt: "Translate the opening exchange into English.",
        choices: [],
        answer: "Nice to meet you. Please treat me kindly today.",
        explanation: "Focus on the polite, reciprocal tone.",
      },
    ],
  },
  {
    id: "food-ramen",
    title: "Food Culture: Ramen Order",
    theme: "food culture",
    difficulty: "N5",
    japanese: "ラーメンを一つください。スープはあっさりでお願いします。",
    romaji: "Raamen o hitotsu kudasai. Suupu wa assari de onegaishimasu.",
    translation: "One ramen, please. Light broth, please.",
    grammar: "Use を with the item you want, and 〜でお願いします for a polite request.",
    vocab: [
      { word: "ラーメン", kana: "ラーメン", meaning: "ramen" },
      { word: "一つ", kana: "ひとつ", meaning: "one item" },
      { word: "あっさり", kana: "あっさり", meaning: "light / not heavy" },
      { word: "スープ", kana: "スープ", meaning: "soup / broth" },
      { word: "お願いします", kana: "おねがいします", meaning: "please / I would like" },
    ],
    kanji: ["一", "店", "汁"],
    dialogueLines: [
      { speaker: "Narration", text: "Ordering at a ramen shop." },
      { speaker: "Customer", text: "ラーメンを一つください。" },
      { speaker: "Staff", text: "スープはあっさりとこってり、どちらにしますか。" },
      { speaker: "Customer", text: "あっさりでお願いします。" },
      { speaker: "Staff", text: "かしこまりました。" },
    ],
    grammarPoints: [
      {
        title: "を + quantity",
        explanation: "Use を to mark the thing you are ordering.",
        example: "ラーメンを一つください。",
      },
      {
        title: "〜でお願いします",
        explanation: "A soft, polite way to specify your preference.",
        example: "あっさりでお願いします。",
      },
      {
        title: "どちら",
        explanation: "Use it when asking someone to choose between two options.",
        example: "あっさりとこってり、どちらにしますか。",
      },
    ],
    exercises: [
      {
        id: "food-ramen-exercise-1",
        type: "multiple-choice",
        prompt: "Which meaning matches あっさり?",
        choices: ["light / not heavy", "very spicy", "expensive", "cold"],
        answer: "light / not heavy",
        explanation: "In food, あっさり means a light, less heavy taste.",
      },
      {
        id: "food-ramen-exercise-2",
        type: "translation",
        prompt: "Translate the order line into English.",
        choices: [],
        answer: "One ramen, please. Light broth, please.",
        explanation: "Focus on the polite request and the item count.",
      },
    ],
  },
  {
    id: "history-samurai",
    title: "Samurai History: Resolve",
    theme: "samurai/history",
    difficulty: "N4",
    japanese: "武士は言葉より行動で示す。礼から学び、心を整える。",
    romaji: "Bushi wa kotoba yori koudou de shimesu. Rei kara manabi, kokoro o totonoeru.",
    translation: "A samurai shows through action rather than words. Learn from respect and steady your heart.",
    grammar: "Use より for comparison and で示す to show how something is expressed.",
    vocab: [
      { word: "武士", kana: "ぶし", meaning: "samurai / warrior" },
      { word: "行動", kana: "こうどう", meaning: "action" },
      { word: "示す", kana: "しめす", meaning: "to show" },
      { word: "礼", kana: "れい", meaning: "respect / bow" },
      { word: "心", kana: "こころ", meaning: "heart / mind" },
    ],
    kanji: ["武", "行", "示"],
    dialogueLines: [
      { speaker: "Narration", text: "A training hall before practice." },
      { speaker: "Teacher", text: "武士は言葉より行動で示す。" },
      { speaker: "Student", text: "礼はどこから学べばいいですか。" },
      { speaker: "Teacher", text: "礼から学び、心を整えなさい。" },
      { speaker: "Student", text: "はい、覚えます。" },
    ],
    grammarPoints: [
      {
        title: "より",
        explanation: "Use より to compare two things.",
        example: "言葉より行動。",
      },
      {
        title: "〜で示す",
        explanation: "Use で to show the means or method.",
        example: "行動で示す。",
      },
      {
        title: "〜から",
        explanation: "Use から to show the starting point or source.",
        example: "礼から学びます。",
      },
    ],
    exercises: [
      {
        id: "history-samurai-exercise-1",
        type: "multiple-choice",
        prompt: "What does 武士 mean in this lesson?",
        choices: ["samurai / warrior", "teacher", "student", "food"],
        answer: "samurai / warrior",
        explanation: "The lesson uses 武士 for the warrior figure.",
      },
      {
        id: "history-samurai-exercise-2",
        type: "translation",
        prompt: "Translate the main sentence into English.",
        choices: [],
        answer: "A samurai shows through action rather than words.",
        explanation: "Focus on the comparison pattern より.",
      },
    ],
  },
  {
    id: "manga-panel",
    title: "Manga Panels: Reaction Shot",
    theme: "manga",
    difficulty: "N5",
    japanese: "えっ、本当に？ そんなはずないよ。",
    romaji: "E, hontou ni? Sonna hazu nai yo.",
    translation: "What? Really? That can't be true.",
    grammar: "Use えっ for surprise and そんなはずない for strong denial.",
    vocab: [
      { word: "えっ", kana: "えっ", meaning: "huh? / what?" },
      { word: "本当に", kana: "ほんとうに", meaning: "really" },
      { word: "そんな", kana: "そんな", meaning: "such / that kind of" },
      { word: "はず", kana: "はず", meaning: "supposed to / expectation" },
      { word: "ない", kana: "ない", meaning: "not exist / not true" },
    ],
    kanji: ["本", "真", "無"],
    dialogueLines: [
      { speaker: "Narration", text: "A manga-style reaction panel after a surprise reveal." },
      { speaker: "Friend", text: "えっ、本当に？" },
      { speaker: "Friend", text: "そんなはずないよ。" },
      { speaker: "Friend", text: "もう一度見てみよう。" },
      { speaker: "Narration", text: "The scene pauses on the shocked expression." },
    ],
    grammarPoints: [
      {
        title: "えっ",
        explanation: "Use えっ to react to surprising news.",
        example: "えっ、本当に？",
      },
      {
        title: "そんなはずない",
        explanation: "Use this to say something should not be the case.",
        example: "そんなはずないよ。",
      },
      {
        title: "本当に",
        explanation: "Add 本当に to ask or stress whether something is really true.",
        example: "本当に？",
      },
    ],
    exercises: [
      {
        id: "manga-panel-exercise-1",
        type: "multiple-choice",
        prompt: "Which phrase shows surprise?",
        choices: ["えっ", "こちらこそ", "どうぞ", "かしこまりました"],
        answer: "えっ",
        explanation: "えっ is the quick reaction sound for surprise.",
      },
      {
        id: "manga-panel-exercise-2",
        type: "translation",
        prompt: "Translate the reaction line into English.",
        choices: [],
        answer: "What? Really? That can't be true.",
        explanation: "The line combines surprise with a strong denial.",
      },
    ],
  },
  {
    id: "daily-life-commute",
    title: "Daily Life: Morning Commute",
    theme: "daily life",
    difficulty: "N5",
    japanese: "電車は少し混んでいますが、毎日この時間に乗ります。",
    romaji: "Densha wa sukoshi konde imasu ga, mainichi kono jikan ni norimasu.",
    translation: "The train is a little crowded, but I ride it at this time every day.",
    grammar: "Use が to connect a contrast and に for time.",
    vocab: [
      { word: "電車", kana: "でんしゃ", meaning: "train" },
      { word: "少し", kana: "すこし", meaning: "a little" },
      { word: "混んでいます", kana: "こんでいます", meaning: "is crowded" },
      { word: "毎日", kana: "まいにち", meaning: "every day" },
      { word: "時間", kana: "じかん", meaning: "time / hour" },
    ],
    kanji: ["電", "車", "毎"],
    dialogueLines: [
      { speaker: "Narration", text: "A quiet morning commute to work or school." },
      { speaker: "Commuter", text: "電車は少し混んでいます。" },
      { speaker: "Commuter", text: "でも、毎日この時間に乗ります。" },
      { speaker: "Friend", text: "朝はいつも同じ時間ですか。" },
      { speaker: "Commuter", text: "はい、だいたい同じです。" },
    ],
    grammarPoints: [
      {
        title: "が",
        explanation: "Use が to connect two thoughts with contrast.",
        example: "混んでいますが、乗ります。",
      },
      {
        title: "に",
        explanation: "Use に for a specific time or moment.",
        example: "この時間に乗ります。",
      },
      {
        title: "毎日",
        explanation: "毎日 means every day and is useful for routines.",
        example: "毎日この時間に乗ります。",
      },
    ],
    exercises: [
      {
        id: "daily-life-commute-exercise-1",
        type: "multiple-choice",
        prompt: "What does 毎日 mean?",
        choices: ["every day", "sometimes", "after lunch", "by train"],
        answer: "every day",
        explanation: "毎日 is the routine word for every day.",
      },
      {
        id: "daily-life-commute-exercise-2",
        type: "translation",
        prompt: "Translate the commute sentence into English.",
        choices: [],
        answer: "The train is a little crowded, but I ride it at this time every day.",
        explanation: "Focus on the contrast and the routine time.",
      },
    ],
  },
  {
    id: "workplace-mail",
    title: "Workplace: Polite Email",
    theme: "workplace",
    difficulty: "N4",
    japanese: "ご確認ありがとうございます。資料を添付しましたので、ご覧ください。",
    romaji: "Gokakunin arigatou gozaimasu. Shiryou o tenpu shimashita node, goran kudasai.",
    translation: "Thank you for checking. I attached the materials, so please take a look.",
    grammar: "Use ご確認ありがとうございます for gratitude and 〜ので for a polite reason.",
    vocab: [
      { word: "確認", kana: "かくにん", meaning: "confirmation / checking" },
      { word: "資料", kana: "しりょう", meaning: "materials / documents" },
      { word: "添付", kana: "てんぷ", meaning: "attachment" },
      { word: "ご覧ください", kana: "ごらんください", meaning: "please look / please see" },
      { word: "ありがとうございます", kana: "ありがとうございます", meaning: "thank you" },
    ],
    kanji: ["確", "資", "添"],
    dialogueLines: [
      { speaker: "Narration", text: "A short business email on a workday." },
      { speaker: "Sender", text: "ご確認ありがとうございます。" },
      { speaker: "Sender", text: "資料を添付しましたので、ご覧ください。" },
      { speaker: "Receiver", text: "承知しました。確認します。" },
      { speaker: "Narration", text: "Polite workplace tone keeps the exchange smooth." },
    ],
    grammarPoints: [
      {
        title: "ご確認ありがとうございます",
        explanation: "A business-style thank you for checking or reviewing something.",
        example: "ご確認ありがとうございます。",
      },
      {
        title: "〜ので",
        explanation: "Use ので to give a polite reason or explanation.",
        example: "資料を添付しましたので、ご覧ください。",
      },
      {
        title: "ご覧ください",
        explanation: "A polite request meaning 'please look.'",
        example: "ご覧ください。",
      },
    ],
    exercises: [
      {
        id: "workplace-mail-exercise-1",
        type: "multiple-choice",
        prompt: "Which phrase is a polite workplace request?",
        choices: ["ご覧ください", "ただいま", "おやすみ", "いってきます"],
        answer: "ご覧ください",
        explanation: "ご覧ください is a polite way to ask someone to look at something.",
      },
      {
        id: "workplace-mail-exercise-2",
        type: "translation",
        prompt: "Translate the email line into English.",
        choices: [],
        answer: "Thank you for checking. I attached the materials, so please take a look.",
        explanation: "Keep the polite business tone in the translation.",
      },
    ],
  },
];

const ACHIEVEMENTS = [
  { name: "First Lesson Completed", unlocked: false },
  { name: "7-Day Streak", unlocked: false },
  { name: "50 Kanji Learned", unlocked: false },
  { name: "100 Words Reviewed", unlocked: false },
  { name: "First Spoken Conversation", unlocked: false },
  { name: "Anime Dialogue Master", unlocked: false },
];

const DAILY_TASKS = [
  { name: "Complete 1 lesson", reward: "+40 XP", complete: false },
  { name: "Review 10 vocabulary items", reward: "+30 XP", complete: false },
  { name: "Practice 3 kanji", reward: "+20 XP", complete: false },
  { name: "Speak 5 sentences", reward: "+50 XP", complete: false },
];

const COSMETICS = [
  { name: "Sakura Theme", cost: 120, owned: false, equipped: false },
  { name: "Ramen Master Icon", cost: 80, owned: false, equipped: false },
  { name: "Manga Panel Background", cost: 160, owned: false, equipped: false },
];

const CHALLENGES = [
  {
    id: "challenge-anime-dialogue",
    title: "7-Day Anime Dialogue Challenge",
    description: "Complete anime dialogue lessons to build streak momentum.",
    category: "lesson",
    targetCount: 3,
    rewardXp: 120,
    rewardCredits: 40,
    claimed: false,
    progress: 0,
  },
  {
    id: "challenge-kanji-sprint",
    title: "Kanji Sprint",
    description: "Hit focused study sessions for kanji practice.",
    category: "study",
    targetCount: 5,
    rewardXp: 150,
    rewardCredits: 50,
    claimed: false,
    progress: 0,
  },
  {
    id: "challenge-listening-week",
    title: "Listening Week",
    description: "Complete listening drills and keep the audio loop going.",
    category: "listening",
    targetCount: 4,
    rewardXp: 100,
    rewardCredits: 35,
    claimed: false,
    progress: 0,
  },
];

export const INITIAL_APP_STATE = {
  view: "learn",
  activeLessonId: "anime-intro",
  toggles: {
    furigana: true,
    romaji: false,
    translation: true,
  },
  progress: {
    xp: 0,
    level: 1,
    credits: 0,
    streak: 0,
    streakFreezeCount: 0,
    kanji: 0,
    vocab: 0,
    speakingMinutes: 0,
    listeningMinutes: 0,
    completedLessons: [],
    reviewedWords: 0,
    speakingSessions: 0,
    listeningExercises: 0,
    completedExercises: [],
    savedWords: [],
    savedKanji: [],
    lessonNotes: {},
  },
  lessons: LESSONS,
  reviews: [],
  kanjiReviews: [],
  achievements: ACHIEVEMENTS,
  dailyTasks: DAILY_TASKS,
  cosmetics: COSMETICS,
  admin: {
    roles: ["Super Admin", "Content Admin", "Support Admin", "Analytics Admin"],
    permissions: {
      roles: [
        { name: "Super Admin", permissions: ["Manage content", "Manage users", "View analytics", "Manage AI usage"] },
        { name: "Content Admin", permissions: ["Manage content", "Manage AI usage"] },
        { name: "Support Admin", permissions: ["Manage users"] },
        { name: "Analytics Admin", permissions: ["View analytics"] },
      ],
      permissions: [
        { name: "Manage content" },
        { name: "Manage users" },
        { name: "View analytics" },
        { name: "Manage AI usage" },
      ],
    },
    aiUsage: {
      dailyRequests: 0,
      monthlyRequests: 0,
      cachedResponses: 0,
      failedRequests: 0,
    },
    siteHealth: "Green",
    maintenanceMode: false,
    announcements: "Practice 5 minutes a day to keep the streak alive.",
    authenticated: false,
    sessionUser: null,
    auditLog: [],
    contentReviewQueue: [],
    users: [],
    challenges: CHALLENGES,
    leaderboard: [],
  },
  roleplay: {
    scenario: "restaurant",
    transcript: [],
  },
  tutor: {
    question: "Ask about grammar, meaning, or nuance.",
    answer: "Use the Practice tab to ask a short question.",
  },
  chest: {
    ready: false,
    lastReward: "None",
  },
  settings: {
    announcements: "Practice 5 minutes a day to keep the streak alive.",
    maintenanceMode: false,
  },
  users: [],
  challenges: CHALLENGES,
  aiUsage: {
    dailyRequests: 0,
    monthlyRequests: 0,
    cachedResponses: 0,
    failedRequests: 0,
  },
};

export const ADMIN_CREDENTIALS = {
  username: "admin",
  password: "fieldguide123",
};
